package com.cloud.network.utils;

public class JuniperNDAPIConstants {
	
	 public static final String PLUGINSTATUS = "PLUGINSTATUS";
	 public static final String NAASDOMAINID = "NAASDOMAINID";
	 public static final String TENANTID = "TENANTID";
	 public static final String USERNAME = "USERNAME";
	 public static final String PASSWORD = "PASSWORD";
	 public static final String NDAPI_SERVER_URL = "NDAPI_SERVER_URL";
	 public static final String NW_ORCHESTRATION_VIA = "NW_ORCHESTRATION_VIA";
	 public static final String CLI = "CLI";
	 public static final String NDAPI = "NDAPI";
	 public static final String NETCONF = "NETCONF";
	 public static final String DEVICE_USER = "DEVICE_USER";
	 public static final String DEVICE_PASSWORD = "DEVICE_PASSWORD";
	 public static final String SWITCHES = "SWITCHES";
	 public static final String ELS_SUPPORTED_DEVICES ="ELS_SUPPORTED_DEVICES";
	 public static final String USE_LLDP = "USE_LLDP";
	 public static final String POST = "POST";
	 public static final String PUT = "PUT";
	 public static final String DELETE = "DELETE";
	 public static final String GET = "GET";
	 public static final String AUTHORIZATION = "Authorization";
	 public static final String ACCEPT = "Accept";
	 public static final String ContentType ="Content-Type";
	 public static final String BASIC ="Basic ";
	 public static final String ELEMENTNAME= "element-name";
	 public static final String HREF = "@href";
	 public static final String PREFIX = "prefix";
	 public static final String DEFAULT_GATEWAY = "default-gateway";
	 public static final String VLANID = "vlan-id";
	 public static final String REQUESTEDACTION = "requested-action";
	 public static final String ACTIVATE = "ACTIVATE";
	 public static final String ACTIVATED = "ACTIVATED";
	 public static final String DEFINED = "DEFINED";
	 public static final String DEACTIVATE = "DEACTIVATE";
	 public static final String MERGE = "MERGE";
	 public static final String NM_STATE = "nm-state";
	 public static final String CHILD_NAAS_SERVICE_ID = "child-id";
	 public static final String NAASSERVICE = "naas-service";
	 public static final String NAASDOMAIN = "naas-domain";
	 public static final String CONNECTIVITY_GROUP = "connectivity-group";
	 public static final String PORT = "port";
	 public static final String REVENUEPORTS = "revenue-ports";
	 public static final String REVENUEPORT = "revenue-port";
	 public static final String L2CS = "l2-connectivity-service";
	 public static final String L3CS = "l3-connectivity-service";
	 public static final String ACCEPT_NAASSERVICE = "application/vnd.juniper.nd.naas-service+json;version=1";
	 public static final String ACCEPT_NAASSDOMAIN = "application/vnd.juniper.nd.naas-domain+json;version=1";
	 public static final String CONTENT_TYPE_NAASSERVICE = "application/vnd.juniper.nd.naas-service+json;version=1;charset=UTF-8";
	 public static final String CONTENT_TYPE_NAASDOMAIN = "application/vnd.juniper.nd.naas-domain+json;version=1;charset=UTF-8";
	 public static final String ACCEPT_L2CS = "application/vnd.juniper.nd.l2-connectivity-service+json;version=1";
	 public static final String CONTENT_TYPE_L2CS = "application/vnd.juniper.nd.l2-connectivity-service+json;version=1;charset=UTF-8";
	 public static final String ACCEPT_PORT = "application/vnd.juniper.nd.port+json;version=1";
	 public static final String CONTENT_TYPE_PORT = "application/vnd.juniper.nd.port+json;version=1;charset=UTF-8";
	 public static final String ACCEPT_CONNECTIVITY_GROUP = "application/vnd.juniper.nd.connectivity-group+json;version=1";
	 public static final String CONTENT_TYPE_CONNECTIVITY_GROUP = "application/vnd.juniper.nd.connectivity-group+json;version=1;charset=UTF-8";
	 public static final String ACCEPT_L3CS = "application/vnd.juniper.nd.l3-connectivity-service+json;version=1";
	 public static final String CONTENT_TYPE_L3CS = "application/vnd.juniper.nd.l3-connectivity-service+json;version=1;charset=UTF-8";
}
